#!/bin/bash

#
# chunkwm config for desktops/large screens
#

#
# NOTE: specify the absolutepath of the file to use for logging.
#       'stdout' and 'stderr' are valid values.
#

chunkc core::log_file stdout

#
# NOTE: specify the desired level of logging.
#
#       - none, debug, warn, error
#

chunkc core::log_level warn

#
# NOTE: specify the absolutepath to the directory to use when
#       loading a plugin. '~' expansion is supported.
#

chunkc core::plugin_dir /usr/local/opt/chunkwm/share/chunkwm/plugins

#
# NOTE: if enabled, chunkwm will monitor the specified plugin_dir
#       and automatically reload any '.so' file that is changed.
#

chunkc core::hotload 0

#
# NOTE: the following are config variables for the chunkwm-tiling plugin.
#

# default:
# use "monocle" layout (like a stack of cards with only the top card visible)
# with large left and right margins
chunkc set global_desktop_mode           monocle
chunkc set global_desktop_offset_top     16
chunkc set global_desktop_offset_bottom  16
chunkc set global_desktop_offset_left    480
chunkc set global_desktop_offset_right   480
chunkc set global_desktop_offset_gap     16

#
# NOTE: syntax for desktop-specific settings
#

# desktops 4 & 5:
# …are where i run full-width, 3-column layouts for coding
# use "bsp" (binary space partition) layout
# with minimal margins

chunkc set 4_desktop_mode                bsp
chunkc set 4_desktop_offset_top          16
chunkc set 4_desktop_offset_bottom       16
chunkc set 4_desktop_offset_left         16
chunkc set 4_desktop_offset_right        16
chunkc set 4_desktop_offset_gap          16

chunkc set 5_desktop_mode                bsp
chunkc set 5_desktop_offset_top          16
chunkc set 5_desktop_offset_bottom       16
chunkc set 5_desktop_offset_left         16
chunkc set 5_desktop_offset_right        16
chunkc set 5_desktop_offset_gap          16

# chunkc set 2_desktop_mode                monocle
# chunkc set 5_desktop_mode                float
# chunkc set 3_desktop_offset_top          190
# chunkc set 3_desktop_offset_bottom       190
# chunkc set 3_desktop_offset_left         190
# chunkc set 3_desktop_offset_right        190
# chunkc set 3_desktop_offset_gap          30
#

chunkc set desktop_padding_step_size     10.0
chunkc set desktop_gap_step_size         5.0

chunkc set bsp_spawn_left                1
chunkc set bsp_optimal_ratio             1.618
chunkc set bsp_split_mode                optimal
chunkc set bsp_split_ratio               0.6

chunkc set monitor_focus_cycle           1
chunkc set window_focus_cycle            monitor

chunkc set mouse_follows_focus           intrinsic
chunkc set window_float_next             0
chunkc set window_region_locked          1

chunkc set mouse_move_window             \"fn 1\"
chunkc set mouse_resize_window           \"fn 2\"
chunkc set mouse_motion_interval         35

chunkc set preselect_border_color        0xffd75f5f
chunkc set preselect_border_width        5

#
# NOTE: these settings require chwm-sa.
#       (https://github.com/koekeishiya/chwm-sa)
#

chunkc set window_float_topmost          0
chunkc set window_fade_inactive          0
chunkc set window_fade_alpha             0.85
chunkc set window_fade_duration          0.25
chunkc set window_use_cgs_move           0

#
# NOTE: the following are config variables for the chunkwm-border plugin.
#

chunkc set focused_border_color          0xff3fffca
chunkc set focused_border_width          2
chunkc set focused_border_radius         6
chunkc set focused_border_skip_floating  0

#
# NOTE: the following are config variables for the chunkwm-ffm plugin.
#

chunkc set ffm_bypass_modifier           fn

#
# NOTE: specify plugins to load when chunkwm starts.
#       if chunkc plugin_dir is not set, the absolutepath is necessary.
#

chunkc core::load border.so
chunkc core::load tiling.so
chunkc core::load ffm.so

#
# NOTE: sample rules for the tiling plugin
#

# desktops
chunkc tiling::rule --owner \"Time Out\" --desktop 1 --follow-desktop
chunkc tiling::rule --owner \"Google Play Music Desktop Player\" --desktop 2 --follow-desktop
chunkc tiling::rule --owner iTunes --desktop 2 --follow-desktop
chunkc tiling::rule --owner Spotify --desktop 2 --follow-desktop
chunkc tiling::rule --owner Messages --desktop 3 --follow-desktop
chunkc tiling::rule --owner WhatsApp --desktop 3 --follow-desktop
chunkc tiling::rule --owner Slack --desktop 3 --follow-desktop
chunkc tiling::rule --owner Atom --desktop 5 --follow-desktop
chunkc tiling::rule --owner \"Visual Studio Code\" --desktop 5 --follow-desktop
chunkc tiling::rule --owner iTerm --desktop 5 --follow-desktop
chunkc tiling::rule --owner Firefox --desktop 6 --follow-desktop

# floats
chunkc tiling::rule --owner \"Alfred Preferences\" --state float
chunkc tiling::rule --owner \"App Store\" --state float
chunkc tiling::rule --owner Docker --state float
chunkc tiling::rule --owner Finder --name Copy --state float
chunkc tiling::rule --owner Steam --state float
chunkc tiling::rule --owner \"System Preferences\" --state float
chunkc tiling::rule --owner Teensy --state float
chunkc tiling::rule --owner \"Toggl Desktop\" --state float

# tiles
chunkc tiling::rule --owner Emacs --except "^$" --state tile
